[package]
name = "onesec_forwarder_lambda_parameter_store_client"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-sdk-ssm = "1.91.0"
onesec_forwarder_lambda_core.path = "../core"
onesec_forwarder_types.path = "../../types"
